JonathonReinhart/staticx

.gitignore
SConstruct
bootloader/SConscript
staticx/.gitignore
staticx/__main__.py
staticx/api.py
staticx/errors.py

Include the bootloader in this package, so the user doesn't need to provide it.

Refactor into a package

---

staticx/api.py

Cleanup staticx temp files

---

.travis.yml
CHANGELOG.md
requirements.txt
staticx/api.py
staticx/archive.py
staticx/constants.py
staticx/errors.py
staticx/utils.py
test/pyinstall/.gitignore
test/pyinstall/app.py
test/pyinstall/run_test.sh

Handle hidden dependencies in apps built with PyInstaller

---

.travis.yml
requirements.txt
test/pyinstall/run_test.sh

ci: Skip PyInstaller test on unsupported Python versions

---

setup.py

More setup.py improvements

---

setup.py
staticx/api.py
staticx/elf.py
staticx/hooks/__init__.py
staticx/hooks/pyinstaller.py

Break out things from api.py into elf.py and hooks/

Refactor staticx package

---

staticx/elf.py

Hide meaningless patchelf warning message

---

staticx/elf.py

Wait for patchelf and check return code

---

.travis.yml

Release wheels built with musl-libc

---

CHANGELOG.md
staticx/api.py
staticx/errors.py
staticx/utils.py

Raise error if output path is a directory

---

.travis.yml
CHANGELOG.md
bootloader/extract.c
staticx/__main__.py
staticx/api.py
staticx/archive.py
test/date.sh

Enable optional compression

---

libtar/encode.c
libtar/extract.c

libtar: Use <sys/sysmacros.h> for makedev() and friends

---

staticx/hooks/pyinstaller.py
staticx/utils.py

Handle subdirectories when extracting Pyinstaller archives

---

staticx/elf.py

Handle shared objects with no dependencies

---

MANIFEST.in
requirements.txt
staticx/elf.py

A few small fixes

---

.travis.yml
CHANGELOG.md
SConstruct
bootloader/SConscript
bootloader/common.h
bootloader/debug.h
bootloader/elfutil.c
bootloader/extract.c
bootloader/main.c
dynversion.py
libtar/extract.c
libtar/libtar.h
libtar/output.c
setup.py
staticx/.gitignore
staticx/__main__.py
staticx/api.py

This helps with debugging bootloader issues.

Use debug build of bootloader if --debug is set

---

staticx/elf.py

`vdso(7)` says:
> The name of the vDSO varies across architectures. It will often show up in things like glibc's `ldd(1)` output. The exact name should not matter to any code, so do not hardcode it.
>
> user ABI | vDSO name
> ------------ | -------------
> ...
> i386 | linux-gate.so.1
> x86-64 | linux-vdso.so.1
> ...
Instead, we look for `ldd` output lines that have a short library name (e.g. `linux-vdso.so.1`) which doesn't start with `/`, and which isn't shown as resolved to some library path. For safety, we also ensure it starts with `linux-` although this could be relaxed if necessary.
Fixes #99

Don't hard-code linux-vdso.so

---

CHANGELOG.md
staticx/archive.py
staticx/utils.py
test/date.sh

Force user program to be executable

---

bootloader/error.h
bootloader/main.c

Minor bootloader enhancements by @cmorty.
Supersedes #105, #106.

Minor bootloader enhancements

---

.travis.yml
CHANGELOG.md
bootloader/main.c
staticx/api.py
staticx/archive.py
test/busybox.sh
test/run_all.sh

Retain original program filename

---

SConstruct
bootloader/SConscript
requirements.txt
setup.py

Similar to #136, these are just more changes I want to get out of the way before #139.

More minor fixes

---

staticx/elf.py

Force utf-8 decoding of patchelf output

---

CHANGELOG.md
staticx/elf.py
test/rpath-origin/SConscript
test/rpath-origin/SConstruct

Fix issue with patchelf --force-rpath not working as expected

---

staticx/elf.py
staticx/hooks/glibc.py
staticx/utils.py
unittest/test_utils.py

Add `ELFFileX`, a class derived from `ELFFile` with all of our custom/convenience methods.

Refactor pyelftools uses

---

CHANGELOG.md
docs/Makefile
docs/index.rst
docs/installation.rst
docs/rpath.rst
docs/troubleshooting.rst
docs/usage.rst

Doc updates

---

CHANGELOG.md
setup.py

Drop support for Python 3.5 and 3.6
