JonathonReinhart/staticx

- bootloader/SConscript
- bootloader/error.c
- bootloader/error.h
- bootloader/main.c
- bootloader/mmap.c
- bootloader/mmap.h
- bootloader/util.c
- bootloader/util.h
- staticx/__main__.py
- staticx/api.py
- staticx/utils.py
By patching the program interpreter and rpath at runtime (to point to our extracted archive directory), we can now run the program directly, instead of launching via the interpreter. This lets `/proc/self/exe` actually point to the application, which is important for applications (like those built by PyInstaller) which need to access their executable file.
> Patch program interpreter and rpath

- bootloader/util.c
ntfw is not included by default  when including ftw.h, a define is required before inclusion of ftw.h in order for gcc to resolve the symbol.
Note, this change is still needed despite changing GCC flags for gnu99 compatibility in SConstruct
> Updating util.c to include required define for ntfw inclusion

- README.md
- bootloader/util.c
- staticx/api.py
- staticx/errors.py
Resolving issue 15-- compatibility with python 2.7.  
Namely, reverting to the older OSError exception instead of the newer FileNotFoundError, and reverting to an older protocol for calling super class constructors for initialization
Also includes some unrelated Readme.MD changes. sorry for the mess.
> 15 python27 compat

- .travis.yml
- requirements.txt
This enables basic building + testing on Travis. Future work will add unit tests and targeted system tests.
> Enable Travis CI

- .gitignore
- MANIFEST.in
- SConstruct
- setup.py
- Don't include prebuilt binaries in an `sdist` package
- Make SCons work better with setup.py
> Improve setup.py

- bootloader/util.c
Travis currently runs ubuntu 14.04 which includes musl 0.9.15-1 which
exhibits a bug where FTW_MOUNT causes problems. We'll just leave off the
flag (which we don't really need anyway) to work on older versions of
musl.
This fixes #25
> bootloader: Leave off FTW_MOUNT in nftw() call

- .travis.yml
- CHANGELOG.md
- README.md
- SConstruct
- bootloader/SConscript
- bootloader/common.h
- bootloader/debug.h
- bootloader/elfutil.c
- bootloader/elfutil.h
- bootloader/extract.c
- bootloader/extract.h
- bootloader/main.c
- libxz/README.md
- libxz/SConscript
- libxz/xz.h
- libxz/xz_config.h
- libxz/xz_crc32.c
- libxz/xz_dec_bcj.c
- libxz/xz_dec_lzma2.c
- libxz/xz_dec_stream.c
- libxz/xz_lzma2.h
- libxz/xz_private.h
- libxz/xz_stream.h
- requirements.txt
- staticx/archive.py
Use the Python `lzma` library to compress the archive tarball in XZ format.
Use XZ Embedded as a custom "tar type" for libtar to decompress the archive at runtime.
This adds a small startup delay. We may, in the future, make the compression optional.
Also, we currently employ the x86 BCJ filter unconditionally. On other architectures, the worst that can happen is a slightly worse compression ratio. In the future, we could detect architectures both in the `staticx` Python code (to select the appropriate filter), and when we build (configure) the bootloader.
Closes #3
> Implement XZ compression

- .travis.yml
This is a better fix for #44, ensuring CC doesn't interfere with
installing Python packages needed.
1a95f89463370f1495d11190a2da73108ce3868f didn't help.
> ci: Unset CC before installing Python packages

- .travis.yml
- CHANGELOG.md
- staticx/__main__.py
- staticx/api.py
- staticx/elf.py
- test/pyinstall/run_test.sh
> Add option to strip binaries

- libxz/SConscript
- libxz/xz_config.h
- staticx/archive.py
- staticx/bcjfilter.py
> Dynamically select XZ BCJ filter

- CHANGELOG.md
- requirements.txt
- setup.py
- staticx/api.py
- staticx/elf.py
- staticx/errors.py
This is a partial fix for #55, ensuring that users don't attempt to use staticx to bundle a 32-bit (compat) binary.
It introduces a dependency on `pyelftools`.
> Check user app bits

- .travis.yml
- setup.py
Python 3.7 needs Xenial (and sudo), see https://github.com/travis-ci/travis-ci/issues/9815.
`scons` needed adding separately for 3.7, this is what happens without it: https://travis-ci.org/hugovk/staticx/builds/445535772
> Add support for Python 3.6 and 3.7

- .travis.yml
- requirements.txt
- staticx/api.py
- staticx/elf.py
- staticx/hooks/pyinstaller.py
- test/pyinstall-cffi/.gitignore
- test/pyinstall-cffi/app.py
- test/pyinstall-cffi/run_test.sh
- test/rpath-origin/.gitignore
- test/rpath-origin/SConscript
- test/rpath-origin/SConstruct
- test/rpath-origin/app.c
- test/rpath-origin/libbar.c
- test/rpath-origin/libbar.h
- test/rpath-origin/libfoo.c
- test/rpath-origin/libfoo.h
- test/rpath-origin/run_test.sh
- test/run_all.sh
This makes a number of fixes which all revolve around using `ldd` to discover dependencies:
- Run `ldd` on executables in their original locations, rather than after they're copied temp directory. This is important if they use `RPATH` which includes `$ORIGIN`
- PyInstaller:
- Extract all binaries before scanning for dependencies. This is important if there are dependencies present in the PyInstaller archive
- Set `LD_LIBRARY_PATH` to the temporary directory where we extract files from the PyInstaller archive
Fixes #61
> Properly handle RPATH $ORIGIN

- .travis.yml
PR #66 moved almost everything from trusty to xenial, but Python 3.4 needed to stay on trusty. This must have been fixed at some point because Scuba can use 3.4 on xenial:
https://github.com/JonathonReinhart/scuba/blob/0244c81ec4/.travis.yml
Not only is this simpler, but it also fixes a problem I was having where "realpath" wasn't available on trusty, but was on xenial (https://travis-ci.org/JonathonReinhart/staticx/builds/522893415).
> Simplify .travis.yml and consistently use xenial

- CHANGELOG.md
- README.md
- bootloader/main.c
- bootloader/util.c
- bootloader/util.h
- test/run_all.sh
- test/staticx-env-vars.sh
This defines two environment variables which are set by the staticx bootloader to communicate runtime information to the wrapped child process:
- `STATICX_BUNDLE_DIR`: The absolute path of the "bundle" directory, the
temporary dir where the archive has been extracted. This closes #5.
- `STATICX_PROG_PATH`: The absolute path of the program being executed. This closes #80.
> Set STATICX_* environment variables to communicate runtime info to child process

- CHANGELOG.md
- staticx/archive.py
Python 3.8 changed the default from GNU_FORMAT to PAX_FORMAT which is not supported by our embedded libtar. Force the creation of older GNU_FORMAT tar files.
Fixes #84
> staticx: Force creation of GNU_FORMAT tar files

- .travis.yml
- CHANGELOG.md
- README.md
- requirements.txt
- setup.py
Previously, we did not include the `backports.lzma` package in the `install_requires` list in `setup.py` because `wheel` didn't support PEP508 environment markers, which we need to indicate that it should only be included for Python < 3.3.
pypa/wheel#172 and pypa/wheel#181 have both been closed, indicating that the issue is fixed in setuptools version 36.2.0. So we can now use the environment markers, and hope users are using a new enough version of setuptools. If not, then they'll simply end up with `backports.lzma` unnecessarily installed.
Fixes #45.
Also re-fixes #44 by reverting 6213896f7345bf7d3c7d0fd08ef437c0b4dbc8af.
> Add backports.lzma to install_requires

- CHANGELOG.md
- staticx/elf.py
- staticx/hooks/pyinstaller.py
- test/pyinstall-aux-static-exec/.gitignore
- test/pyinstall-aux-static-exec/app.py
- test/pyinstall-aux-static-exec/app.spec
- test/pyinstall-aux-static-exec/aux.c
- test/pyinstall-aux-static-exec/auxlist.py
- test/pyinstall-aux-static-exec/run_test.sh
- test/run_all.sh
This PR updates the PyInstaller hook to ignore static executables or other `BINARY` files that cause `ldd` to choke when looking for dependencies.
This fixes #78.
> PyInstaller: Ignore static executables and other oddities

- .travis.yml
- README.md
- setup.py
We want to set CC only when building a wheel. This happens in two places:
- When running "python setup.py bdist_wheel" for testing
- When letting Travis build a wheel for pypi deployment
We specifically do *not* want to set CC when running "pip install",
otherwise we'll try to use musl-libc when building other packages'
extensions:
- When running `pip install requirements.txt` for dev/test deps
- When running `pip install *.whl` for testing
History:
- #44 first noticed that setting CC interfered with "pip install"
- 0a2deae6 tried to fix this with `BOOTLOADER_CC`...
- ...but that led to #48 where the released wheels weren't built with musl because it only handled the test, and not the deploy job
- #49 tried to fix this with "skip_cleanup: true" but that didn't work
- #50 then fixed it by …
> Handle BOOTLOADER_CC in setup.py

- bootloader/main.c
- test/staticx-env-vars.sh
`$TMPDIR` is a *de facto* standard environment variable which specifies an alternative to `/tmp`, respected by many applications, e.g.:
- `bash(1)`
- `busybox(1)`
- `mktemp(1)`
- `tempfile(1)`
This updates the staticx bootloader to also respect `$TMPDIR`.
This was inspired by the request in #97.
> Respect $TMPDIR

- .travis.yml
- CHANGELOG.md
- setup.py
Python 3.4 is EOL since 2019-03-18 and is no longer supported by PyYAML 5.3.
See #107
> Drop support for Python 3.4

- .travis.yml
- requirements.txt
- run_unit_tests.sh
- staticx/elf.py
- unittest/test_elf.py
This adds a unit test for `ldd` output parsing, and makes it easy to add additional tests in the future.
Makes progress towards #27
> Add unit tests

- bootloader/main.c
Introduced in ba6e752
Fixes #119
Tested against GCC9
```
$ staticx $(which date) date.sx
$ ./date.sx
Wed 29 Jan 2020 07:35:20 AM EST
$ TMPDIR=/nonexist ./date.sx
date.sx: Failed to create temporary directory in /nonexist: No such file or directory
```
> Fix NULL tmpdir error message

- staticx/elf.py
- unittest/test_elf.py
The previous logic introduced in #102 was somewhat dubious. This corrects that logic and adds a unit test for the reported problematic output.
Fixes #116
> Correct handling of absolute path symlink in ldd output

- CHANGELOG.md
- staticx/utils.py
- unittest/test_utils.py
This fixes these warnings from `ldd`:
```
ldd: warning: you do not have execution permission for `/tmp/staticx-pyi-fe35tk1i/_asyncio.cpython-38-x86_64-linux-gnu.so'
```
There was code to handle this, but this bug was introduced in 2d31b398 when `make_executable` stopped having any effect.
> Fix ldd "you do not have execution..." warning

- .travis.yml
- README.md
- setup.cfg
- setup.py
- staticx/__main__.py
- staticx/archive.py
- staticx/hooks/pyinstaller.py
- staticx/utils.py
- staticx/version.py
- test/pyinstall-aux-static-exec/app.py
- test/pyinstall-cffi/app.py
- test/pyinstall/app.py
Python 2.7 is effectively dead as of 2020 Jan 1. This PR removes support for Python 2.7 entirely, and joins the company of other projects that are now Python 3 only.
There is extra code that StaticX has to maintain to keep support for Python 2.7. By dropping this version of Python, StaticX can move forward unencumbered by legacy issues.
Also, it enables support or simplifies implementation of new features (e.g. #114).
Closes #107
*Does anyone have major heartburn with this change?*
> Remove support for Python 2.7

- SConstruct
- setup.py
- staticx/.gitignore
- staticx/__main__.py
- staticx/api.py
- staticx/assets.py
- staticx/hooks/__init__.py
- staticx/hooks/pyinstaller.py
- staticx/utils.py
This is in preparation for #129.
1. Move to `assets/$MODE/bootloader`
2. Use `pkg_resources.resource_stream`
3. Rework `SConstruct` to improve clarity / extensibility
4. Rework hook API to improve extensibility
> Reorganize the way the bootloader is accessed

- staticx/archive.py
- staticx/elf.py
- staticx/errors.py
- staticx/hooks/pyinstaller.py
- unittest/test_elf.py
This removes some more remnants of Python 2.7 compatibility and uses more Python 3 features:
- Effectively revert the remnants of 0d659d9214cb604c2ab3d33706aba7208641fea2:
- Python 3 `super`: `super(Foo, self)` --> `super()`
- Use `FileNotFoundError` instead of `OSError` + `e.errno == errno.ENOENT`:
- Use Python 3 new-style classes: `class Foo(object):` --> `class Foo:`
- Use `subprocess.run()`
> Remove more Python 2.7 compatibility cruft

- bootloader/elfutil.h
- bootloader/main.c
This MR adds unofficial support for StaticX in native 32-bit (e.g. i386) environments. It does *not* address "multiarch" environments (#55).
I say "unofficial" because Travis doesn't support 32-bit environments, and I haven't yet  moved away from Travis (#124).
Fixes #144
> Fix bootloader for native 32-bit builds

- .travis.yml
- setup.py
Indicate that we are effectively "manylinux1" compliant, even though we don't build with their tools, we have static Linux assets which are OS and machine dependent.
Fixes #150
---
Thinking ahead, #55 gets even more complicated because if we include bootloaders for `i386` and `x86_64` (any maybe even other architectures!) then our wheel would be better described as `manylinux1_any`, which isn't valid.
> setup.py: Override plat_name for bdist_wheel to manylinux1

- MANIFEST.in
There were entries missing from `MANIFEST.in`:
- #139 forgot to add `libnssfix/` and `site_scons/`
- 3bdff7c forgot to add `dynversion.py`
Closes #152
> Fix broken source distributions

- site_scons/site_tools/stubgen.py
> Fix bug where SCons v4.1.0 causes libnssfix to be built incorrectly.

- requirements.txt
This is a quick fix for the CI test failures associated with  #170
> Pin pyinstaller at 4.0 in requirements.txt

- CHANGELOG.md
- staticx/elf.py
- staticx/hooks/glibc.py
This fixes the bug introduced in #139, by returning `None` and handling that in the only consumer.
I want to add a test that covers this but it is difficult:
- Unit test: It's a pain in the ass to write unit tests which make assertions about ELF input files, without checking-in binaries, which I'm not a fan of.
- Integration test: I tried to test staticx against a musl-libc-linked executable, but it failed with #178.
I'd like to improve testing of staticx in lots of ways, but this PR clearly fixes the problem at hand.
Fixes #177  
Supersedes #176
> Fix issue with get_section() erroneously returning KeyError

- CHANGELOG.md
- staticx/elf.py
> Persist LD_LIBRARY_PATH when invoking ldd

- CHANGELOG.md
- staticx/api.py
This PR was motivated by noticing this line:
https://github.com/JonathonReinhart/staticx/blob/159fba33/staticx/api.py#L177
I think this could cause some symlinks to get missed if `--strip` was passed.
I decided to just re-write this code to be safer, and also only copy libraries lazily before we modify them.
The order of operations looks to be correct:
```
INFO:root:Processing library libnss_files.so.2 (/lib/x86_64-linux-gnu/libnss_files.so.2)
INFO:root:Adding Symlink libnss_files.so.2 => libnss_files-2.31.so
INFO:root:Copying /lib/x86_64-linux-gnu/libnss_files-2.31.so to /tmp/staticx-archive-4hx7iz7r/libnss_files-2.31.so
INFO:root:Stripping library /tmp/staticx-archive-4hx7iz7r/libnss_files-2.31.so
DEBUG:root:Running ['strip', '/tmp/staticx-archive-4hx7iz7r/libnss_files-2.31.so'] …
```
> Lazily copy libraries before modifying and rework add_library()

- CHANGELOG.md
- staticx/hooks/glibc.py
This fixes #203
Supersedes #200
> Fix ldd warning about not have execution permission for libnssfix.so

- CHANGELOG.md
- staticx/api.py
When `-l` is used, `StaticxGenerator.add_library()` is called before `.generate()`. In this case, `.tmpdir` is `None`. If `work_on_copy()` is subsequently called because the library needs to be modified by staticx (either because `--strip` is given, or because its RPATH is about to be removed), then `.tmpdir` is used without being set.
This simply moves the `.tmpdir` creation into `StaticxGenerator.__init__`.
This isn't the best solution; you shouldn't really do a bunch of filesystem things in `__init__` -- specifically, if one of the things triggers an exception, then no cleanup will be performed (because `__exit__` will not be called). I'm not sure what the best solution is, though. Perhaps creating temp files in `__enter__`, or adding an `initialize()` API (and all of the mechanics …
> Fix bug causing crash when -l is used with a library needing to be modified by staticx

- CHANGELOG.md
- staticx/api.py
- staticx/archive.py
Fixes #223 
Thanks @liujin1993 for helping to track this down.
> Ignore the case where a library symlink has the same basename as its target

- CHANGELOG.md
- staticx/version.py
Also replace some old os.path() code with pathlib
> Don't crash if .git/ is present but git is not installed

- CHANGELOG.md
- SConstruct
- libtar/decode.c
- libtar/extract.c
- libtar/handle.c
- libtar/libtar.h
- libtar/output.c
glibc warns us that we shouldn't call functions like `getpwnam()` from a statically-linked application:
```
decode.c:(.text+0x88): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
The reason is that it will actually dlopen() the libnss libraries, and then possibly explode.
This PR eliminates the `getpwnam`/`getgrnam` calls from `libtar`, and adds a linker flag to make sure it doesn't happen again.
Note that libtar keeps losing more and more fingers, but that's okay because we don't really need much of its functionality. See also #229 because this is annoying.
Fixes #227.
> Eliminate problematic getxxnam() calls in bootloader

- staticx/hooks/pyinstaller.py
https://github.com/JonathonReinhart/staticx/issues/235 https://github.com/pyinstaller/pyinstaller/issues/7560 
This adds support for the new pyinstaller > 5.10 syntax for pyi_archive tocs.
@JonathonReinhart I tested this locally and it seems to be working and the pytests pass, but I'm not sure how I would add additional unit testing for this code.
> fix: update to support new pyinstaller 5.10 syntax

- CHANGELOG.md
- staticx/hooks/pyinstaller.py
Where #236 adapted the new API to the old API with `if pre_510` checks, this takes the opposite approach: Use the new API, and add an adapter class to adapt the old API to the new.
Benefits:
- No more `if pre_510` checks in the middle of processing code.
- Removing the legacy behavior becomes trivial: delete the adapter.
Tested:
```shell
git clean -fdx test/
pip install pyinstaller==5.9
./test/run_all.sh
git clean -fdx test/
pip install pyinstaller==5.10
./test/run_all.sh
```
> staticx: Rework code for PyInstaller pre-5.10

- CHANGELOG.md
- staticx/hooks/pyinstaller.py
This changes the pre-5.10 version detection to be exactly that, rather than inferring from the presence of `CTOCReader`.
This also explicitly fails on PyInstaller 4.1 and 4.2 (#170).
Fixes: #170
Tested: Run `test/pyinstall/run_test.sh` for all versions of PyInstaller from 4.0 through 5.10.
> staticx: Directly detect PyInstaller version and act accordingly

- .github/workflows/build-test.yml
Targetting the branch for #194, this fixes the problem mentioned in https://github.com/JonathonReinhart/staticx/pull/194#issuecomment-977538789 by using the deadsnakes action to set up python.
Also updates the version matrix to the currently supported versions of python. CI is green on this branch (https://github.com/jmsmkn/staticx/actions/runs/2344440898) but the tests fail against master as the branch is a few commits behind.
#124 
#193
> Use deadsnakes action and update python versions in CI

- .github/workflows/build-test.yml
- test/pyinstall-lib-runpath/app.py
> Move from Travis to GitHub Actions

- setup.py
- site_scons/site_tools/nsswitchconf.py
- site_scons/site_tools/stubgen.py
- staticx/__main__.py
- staticx/api.py
- staticx/archive.py
- staticx/assets.py
- staticx/elf.py
- staticx/errors.py
- staticx/extract.py
- staticx/hooks/glibc.py
- staticx/hooks/pyinstaller.py
- staticx/version.py
- test/pyinstall/app.py
1. Where appropriate, convert to [f-strings](https://peps.python.org/pep-0498/). This was accomplished using `flynt` (https://github.com/ikamensh/flynt) with manual review and a few changes.
2. Take advantage of the new `subprocess.run()` arguments: `text`/`encoding` and `capture_output`.
Closes #246
Reference: https://github.com/JonathonReinhart/scuba/pull/206
> Use Python 3.7 language features

- .github/workflows/build-test.yml
- CHANGELOG.md
- SConstruct
- libnssfix/SConscript
- site_scons/conftest.py
Previously, `libnssfix.so` would [unconditionally link against](https://github.com/JonathonReinhart/staticx/blob/fe8c1e8de9b0ef7201ca9dcfcfeef5e311ce26f5/libnssfix/SConscript#L57) `libnss_files` and `libnss_dns`, as those are the only two libraries ("services" in NSS parlance)  specified in our [`nsswitch.conf`](https://github.com/JonathonReinhart/staticx/blob/main/libnssfix/nsswitch.conf).
As of GLIBC 2.34, the `files` and `dns` NSS "modules" are built-in to libc (https://github.com/bminor/glibc/commit/6212bb67f4695962748a5981e1b9fea105af74f6 and https://github.com/bminor/glibc/commit/e1fcf21474c5b522fdad4ac0191d5dcc3271dba6). While `libnss_files.so.2` and `libnss_dns.so.2` still exist, they are empty stubs (bminor/glibc@9ed48feed8c268e98baf00f3608d85dafb8215f3), and there are no …
> Fix broken nssfix build on newer glibc

- .github/workflows/build-test.yml
- CHANGELOG.md
- SConstruct
- libnssfix/SConscript
- site_scons/conftest.py
Revert PR #255 
https://github.com/JonathonReinhart/staticx/pull/255#issuecomment-1630120893
> Revert #255

- .github/workflows/build-test.yml
- test/nss-isolated/run_test.sh
- test/pyinstall/run_test.sh
This is what was used in .travis.yml
Closes #258
> ci: Set TEST_DOCKER_IMAGE=centos:5

- .github/workflows/build-test.yml
- CHANGELOG.md
- libnssfix/SConscript
- site_scons/site_tools/nsswitchconf.py
- test/no-default-lib/run_test.sh
This takes a different approach than #255 by simply linking against the `libnss_*.so.2` SONAME explicitly, rather than the normal method of passing `-lnss_*`. This works because the `.so.2` stubs still exist on GLIBC >=2.34.
Fixes #245 (take 2)
> Fix broken nssfix build on newer glibc (take 2)

- staticx/elf.py
- staticx/hooks/pyinstaller.py
Previously, if a non-ELF file appeared in a PyInstaller archive as a "binary" file, staticx would crash when open_elf() raised an InvalidInputError.
Rename is_dynamic() to is_dynamic_elf() to make it clear that it now returns False if the file is not an ELF file at all.
Fixes #268.
> staticx: Don't raise exception from is_dynamic_elf

- pyproject.toml
- staticx/version.py
pkg_resources is deprecated:
https://setuptools.pypa.io/en/latest/pkg_resources.html
This prefers importlib.metadata (introduced in Python 3.8) and uses the backport importlib_metadata for Python 3.7 (to be removed in #264).
Fixes #266
Reference: https://github.com/JonathonReinhart/scuba/pull/247
> staticx: Use importlib.metadata over pkg_resources for getting version

- CHANGELOG.md
- pyproject.toml
- staticx/assets.py
- staticx/version.py
Replace `pkg_resources.resource_stream()` with `importlib_resources.files().joinpath().open()`.
Fixes #266 (again).
> staticx: Use importlib.resources over pkg_resources for asset access
